"""
Setup Mosquito Detection Project Structure
==========================================
Stage 3: Prepare the dataset for YOLO training

This script:
1. Creates the project directory structure
2. Copies images and labels to the new structure
3. Creates data.yaml
4. Verifies all files are copied correctly
"""

import os
import shutil
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

# Source dataset (Roboflow download)
SOURCE_DATASET = Path(r"F:\Research Project\Mosquito Detection Dataset.v4i.yolov11")

# Target project directory
PROJECT_ROOT = Path(r"E:\Claude local session\mosquito-detection")

# Class names from the dataset
CLASS_NAMES = ['aegypti', 'albopictus', 'anopheles', 'culex', 'culiseta', 'japonicus-koreicus']

# =============================================================================


def create_directory_structure():
    """Create the project directory structure"""
    print("\n" + "="*60)
    print("CREATING PROJECT DIRECTORY STRUCTURE")
    print("="*60)

    dirs_to_create = [
        PROJECT_ROOT,
        PROJECT_ROOT / "dataset",
        PROJECT_ROOT / "dataset" / "images",
        PROJECT_ROOT / "dataset" / "images" / "train",
        PROJECT_ROOT / "dataset" / "images" / "val",
        PROJECT_ROOT / "dataset" / "images" / "test",
        PROJECT_ROOT / "dataset" / "labels",
        PROJECT_ROOT / "dataset" / "labels" / "train",
        PROJECT_ROOT / "dataset" / "labels" / "val",
        PROJECT_ROOT / "dataset" / "labels" / "test",
        PROJECT_ROOT / "models",
        PROJECT_ROOT / "results",
    ]

    for dir_path in dirs_to_create:
        dir_path.mkdir(parents=True, exist_ok=True)
        print(f"[OK] Created: {dir_path}")

    print(f"\n[SUCCESS] Directory structure created at: {PROJECT_ROOT}")


def copy_files(source_split, target_split, file_type='images'):
    """
    Copy images or labels from source to target directory.

    Args:
        source_split: 'train', 'valid', or 'test'
        target_split: 'train', 'val', or 'test'
        file_type: 'images' or 'labels'
    """
    source_dir = SOURCE_DATASET / source_split / file_type
    target_dir = PROJECT_ROOT / "dataset" / file_type / target_split

    if not source_dir.exists():
        print(f"[WARNING] Source directory not found: {source_dir}")
        return 0

    # Get all files
    if file_type == 'images':
        files = list(source_dir.glob('*.jpg')) + list(source_dir.glob('*.png')) + list(source_dir.glob('*.jpeg'))
    else:  # labels
        files = list(source_dir.glob('*.txt'))

    if not files:
        print(f"[WARNING] No files found in: {source_dir}")
        return 0

    # Copy files
    print(f"\nCopying {len(files)} {file_type} from {source_split} to {target_split}...")

    for index, file_path in enumerate(files, start=1):
        target_path = target_dir / file_path.name
        shutil.copy2(file_path, target_path)
        print(f"  Copied {index}/{len(files)}: {file_path.name}")

    return len(files)


def reorganize_dataset():
    """Copy all images and labels to the new structure"""
    print("\n" + "="*60)
    print("COPYING DATASET FILES")
    print("="*60)

    stats = {
        'images': {'train': 0, 'val': 0, 'test': 0},
        'labels': {'train': 0, 'val': 0, 'test': 0}
    }

    # Map source splits to target splits
    # Note: Roboflow uses 'valid', we want 'val'
    split_mapping = [
        ('train', 'train'),
        ('valid', 'val'),
        ('test', 'test')
    ]

    for source_split, target_split in split_mapping:
        # Copy images
        num_images = copy_files(source_split, target_split, 'images')
        stats['images'][target_split] = num_images

        # Copy labels
        num_labels = copy_files(source_split, target_split, 'labels')
        stats['labels'][target_split] = num_labels

    # Print summary
    print("\n" + "="*60)
    print("COPY SUMMARY")
    print("="*60)

    for split in ['train', 'val', 'test']:
        img_count = stats['images'][split]
        lbl_count = stats['labels'][split]
        match = "MATCH" if img_count == lbl_count else "MISMATCH!"
        print(f"{split.upper():5s}: {img_count:5d} images, {lbl_count:5d} labels [{match}]")

    total_images = sum(stats['images'].values())
    total_labels = sum(stats['labels'].values())
    print(f"{'TOTAL':5s}: {total_images:5d} images, {total_labels:5d} labels")

    return stats


def create_data_yaml():
    """Create the data.yaml configuration file"""
    print("\n" + "="*60)
    print("CREATING data.yaml")
    print("="*60)

    # Use relative paths from the project root
    data_yaml_content = f"""# Mosquito Detection Dataset Configuration
# Generated by setup_project_structure.py

# Dataset paths (relative to this file)
path: {str(PROJECT_ROOT)}  # dataset root dir
train: dataset/images/train  # train images (relative to 'path')
val: dataset/images/val      # val images (relative to 'path')
test: dataset/images/test    # test images (relative to 'path')

# Classes
nc: {len(CLASS_NAMES)}  # number of classes
names: {CLASS_NAMES}  # class names

# Dataset info
dataset_name: Mosquito Detection Dataset
version: v4i
source: Roboflow Universe
image_size: 640
"""

    yaml_path = PROJECT_ROOT / "data.yaml"

    with open(yaml_path, 'w') as f:
        f.write(data_yaml_content)

    print(f"[OK] Created: {yaml_path}")
    print(f"\ndata.yaml contents:")
    print("-" * 60)
    print(data_yaml_content)
    print("-" * 60)


def verify_dataset():
    """Verify the dataset structure and file integrity"""
    print("\n" + "="*60)
    print("VERIFYING DATASET")
    print("="*60)

    issues = []

    # Check data.yaml exists
    yaml_path = PROJECT_ROOT / "data.yaml"
    if not yaml_path.exists():
        issues.append("data.yaml not found")
    else:
        print("[OK] data.yaml exists")

    # Verify each split
    for split in ['train', 'val', 'test']:
        images_dir = PROJECT_ROOT / "dataset" / "images" / split
        labels_dir = PROJECT_ROOT / "dataset" / "labels" / split

        if not images_dir.exists():
            issues.append(f"Images directory missing: {images_dir}")
            continue

        if not labels_dir.exists():
            issues.append(f"Labels directory missing: {labels_dir}")
            continue

        # Get files
        image_files = {f.stem for f in images_dir.glob('*.jpg')} | {f.stem for f in images_dir.glob('*.png')}
        label_files = {f.stem for f in labels_dir.glob('*.txt')}

        # Check for missing labels
        missing_labels = image_files - label_files
        extra_labels = label_files - image_files

        print(f"\n{split.upper()} split:")
        print(f"  Images: {len(image_files)}")
        print(f"  Labels: {len(label_files)}")

        if missing_labels:
            print(f"  [WARNING] {len(missing_labels)} images without labels")
            issues.append(f"{split}: {len(missing_labels)} images without labels")
        else:
            print(f"  [OK] All images have labels")

        if extra_labels:
            print(f"  [WARNING] {len(extra_labels)} labels without images")
            issues.append(f"{split}: {len(extra_labels)} extra labels")

    # Print final verdict
    print("\n" + "="*60)
    if issues:
        print("[WARNING] Issues found:")
        for issue in issues:
            print(f"  - {issue}")
    else:
        print("[SUCCESS] Dataset verification passed!")
    print("="*60)


def create_readme():
    """Create a README.md file for the project"""
    readme_content = """# Mosquito Detection with YOLOv11

## Project Structure

```
mosquito-detection/
│
├── dataset/
│   ├── images/
│   │   ├── train/      # Training images
│   │   ├── val/        # Validation images
│   │   └── test/       # Test images
│   │
│   └── labels/
│       ├── train/      # Training labels
│       ├── val/        # Validation labels
│       └── test/       # Test labels
│
├── data.yaml           # Dataset configuration
├── train.py            # Training script
├── predict.py          # Prediction script
├── evaluate.py         # Evaluation script
├── models/             # Trained models
├── results/            # Training results
└── README.md           # This file
```

## Dataset Information

- **Dataset**: Mosquito Detection Dataset v4i
- **Source**: Roboflow Universe
- **Classes**: 6 mosquito species
  - aegypti
  - albopictus
  - anopheles
  - culex
  - culiseta
  - japonicus-koreicus
- **Image Size**: 640x640 pixels
- **Format**: YOLO (normalized bounding boxes)

## Splits

- **Train**: 6,633 images
- **Validation**: 670 images
- **Test**: 369 images
- **Total**: 7,672 images

## Usage

### Training

```bash
python train.py
```

### Prediction

```bash
python predict.py --image path/to/image.jpg
```

### Evaluation

```bash
python evaluate.py
```

## Notes

- All images are 640x640 pixels
- Labels are in YOLO format (normalized coordinates)
- Each label file corresponds to one image with the same filename
"""

    readme_path = PROJECT_ROOT / "README.md"

    with open(readme_path, 'w') as f:
        f.write(readme_content)

    print(f"\n[OK] Created: {readme_path}")


def main():
    """Main function to set up the project"""
    print("\n" + "="*60)
    print("MOSQUITO DETECTION PROJECT SETUP")
    print("="*60)
    print(f"\nSource: {SOURCE_DATASET}")
    print(f"Target: {PROJECT_ROOT}")

    # Check if source exists
    if not SOURCE_DATASET.exists():
        print(f"\n[ERROR] Source dataset not found: {SOURCE_DATASET}")
        print("Please verify the path and try again.")
        return

    # Step 1: Create directory structure
    create_directory_structure()

    # Step 2: Copy dataset files
    stats = reorganize_dataset()

    # Step 3: Create data.yaml
    create_data_yaml()

    # Step 4: Create README
    create_readme()

    # Step 5: Verify everything
    verify_dataset()

    # Final message
    print("\n" + "="*60)
    print("SETUP COMPLETE!")
    print("="*60)
    print(f"\nYour project is ready at: {PROJECT_ROOT}")
    print("\nNext steps:")
    print("1. Run the verification script: python verify_prepared_dataset.py")
    print("2. Visualize samples: python visualize_samples.py")
    print("3. Proceed to Stage 4: Training")


if __name__ == "__main__":
    main()
